import { Metadata, Viewport } from 'next';

import { Env } from './env';

const defaultQueryOption = {
  retry: 0,
  refetchOnMount: true,
  refetchOnWindowFocus: false,
  refetchOnReconnect: false,
  // With SSR, we usually want to set some default staleTime
  // above 0 to avoid refetching immediately on the client
  staleTime: 60 * 1000,
};

export const locales = ['en', 'vi'] as const;
export const localePrefix = locales.map((el) => `/${el}`);
export type Locale = (typeof locales)[number];

const localeNames: Record<Locale, string> = {
  en: 'English',
  vi: 'Việt Nam',
};
const metadata: Metadata = {
  // Output: <title>About | Create Next App</title>
  title: {
    template: '%s | NextJS Boilerplate',
    default: 'NextJS Boilerplate',
  },
  description: 'Generated by NextJS Boilerplate',
  keywords: ['Next.js', 'React', 'Typescript'],
  openGraph: {
    type: 'website',
    title: {
      template: '%s | NextJS Boilerplate',
      default: 'NextJS Boilerplate',
    },
    description: 'Generated by NextJS Boilerplate',
    images: [
      'https://cdn.prod.website-files.com/648fc4ed35d6666c4a56f9a6/6685b127d495dcad47db87c5_Vipasana_LockupGradient-p-500.png', // 3x2
    ], // IMPORTANT
    siteName: 'NextJS Boilerplate',
    // url: `${Env.NEXT_PUBLIC_DOMAIN}%s`,
  },
  // Update ICON LOGO
  icons: [
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '48x48',
      type: 'image/png',
      rel: 'apple-touch-icon',
    },
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '48x48',
      type: 'image/png',
    },
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '72x72',
      type: 'image/png',
    },
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '96x96',
      type: 'image/png',
    },
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '144x144',
      type: 'image/png',
    },
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '168x168',
      type: 'image/png',
    },
    {
      url: 'https://presensastatefulstack-presensadatabasecredentials-iawl00l6t403.s3.amazonaws.com/logo+(3).png',
      sizes: '192x192',
      type: 'image/png',
    },
  ],
  twitter: {
    card: 'summary_large_image',
    site: '@Home',
    creator: '@creator',
    images:
      'https://cdn.prod.website-files.com/648fc4ed35d6666c4a56f9a6/6685b127d495dcad47db87c5_Vipasana_LockupGradient-p-500.png', // 3x2
  },
  metadataBase: new URL(Env.NEXT_PUBLIC_DOMAIN || ''),
  robots: {
    index: true,
    follow: true,
    noarchive: true,
    nosnippet: true,
    noimageindex: true,
    nocache: true,
  },
  applicationName: 'Next.js',
  authors: [{ name: 'Hoang Phan', url: 'https://nextjs.org' }],
  referrer: 'origin-when-cross-origin',
  creator: 'Hoang Cong Phan',
  publisher: 'Hoang Cong Phan',
  generator: 'Hoang Cong Phan',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'cyan' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1.5,
  minimumScale: 0.9,
  userScalable: true,
};

export const AppConfigs = {
  name: 'Nextjs Boilerplate',
  locales,
  localeNames,
  defaultLocale: 'en' as Locale,
  defaultQueryOption,
  metadata,
  viewport,
};

export const paginateInitialize = {
  limit: 30,
};

export const REGEX = {
  email:
    /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  alphabetAndNumber: /^[a-z0-9]+$/i,
  alphabet: /^[^\d]*$/,
  noSpace: /^\S*$/,
  password:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*_-])[A-Za-z\d!@#$%^&*_-]{8,}$/,
  phone: /(84|0[3|5|7|8|9])+([0-9]{8})\b/,
};

export const cookieKeys = {
  accessToken: 'auth',
  refreshToken: 'refresh-token',
};
