import { Metadata, Viewport } from 'next';

import { Env } from './env';

const defaultQueryOption = {
  retry: 0,
  refetchOnMount: true,
  refetchOnWindowFocus: false,
  refetchOnReconnect: false,
  // With SSR, we usually want to set some default staleTime
  // above 0 to avoid refetching immediately on the client
  staleTime: 60 * 1000,
};

export const locales = ['en', 'vi'] as const;
export const localePrefix = locales.map((el) => `/${el}`);
export type Locale = (typeof locales)[number];

const localeNames: Record<Locale, string> = {
  en: 'English',
  vi: 'Việt Nam',
};
const metadata: Metadata = {
  // Output: <title>About | Create Next App</title>
  title: {
    template: '%s | NextJS Boilerplate',
    default: 'NextJS Boilerplate',
  },
  description: 'Generated by NextJS Boilerplate',
  applicationName: 'Next.js',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next.js', 'React', 'Typescript'],
  authors: [{ name: 'Hoang Phan', url: 'https://nextjs.org' }],
  creator: 'Hoang Cong Phan',
  publisher: 'Hoang Cong Phan',
  generator: 'Hoang Cong Phan',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    title: {
      template: '%s | NextJS Boilerplate',
      default: 'NextJS Boilerplate',
    },
    description: 'Generated by NextJS Boilerplate',
    images: ['https://cdn3.ivivu.com/2023/10/du-lich-sai-gon-ivivu1.jpg'], // IMPORTANT
    siteName: 'NextJS Boilerplate',
    url: `${Env.NEXT_PUBLIC_DOMAIN}`,
  },
  robots: {
    index: true,
    follow: true,
    noarchive: true,
    nosnippet: true,
    noimageindex: true,
    nocache: true,
  },
  metadataBase: new URL(Env.NEXT_PUBLIC_DOMAIN || ''),
  icons: [
    // {
    //   rel: 'apple-touch-icon',
    //   url: '/apple-touch-icon.png',
    // },
    // {
    //   rel: 'icon',
    //   type: 'image/png',
    //   sizes: '32x32',
    //   url: '/favicon-32x32.png',
    // },
    // {
    //   rel: 'icon',
    //   type: 'image/png',
    //   sizes: '16x16',
    //   url: '/favicon-16x16.png',
    // },
    {
      rel: 'icon',
      url: '/favicon.ico',
    },
  ],
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'cyan' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1.5,
  minimumScale: 0.9,
  userScalable: true,
};

export const AppConfigs = {
  name: 'Nextjs Boilerplate',
  locales,
  localeNames,
  defaultLocale: 'en' as Locale,
  defaultQueryOption,
  metadata,
  viewport,
};

export const paginateInitialize = {
  limit: 30,
};

export const REGEX = {
  email:
    /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  alphabetAndNumber: /^[a-z0-9]+$/i,
  alphabet: /^[^\d]*$/,
  noSpace: /^\S*$/,
  password:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*_-])[A-Za-z\d!@#$%^&*_-]{8,}$/,
  phone: /(84|0[3|5|7|8|9])+([0-9]{8})\b/,
};

export const sessionKeys = {
  auth: 'auth',
};

export const cookieKeys = {
  refreshToken: 'refresh-token',
};
